### ISSUE TITLE
Potodo cannot be executed with github enabled remotely

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/Potodo#25]
```
(python-docs-i18n) ➜  ~ potodo -p Projects/python-docs-fr
Traceback (most recent call last):
  File "/Users/seluj78/.venvs/python-docs-i18n/bin/potodo", line 8, in <module>
    sys.exit(main())
  File "/Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages/potodo/potodo.py", line 232, in main
    args.no_reserved,
  File "/Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages/potodo/potodo.py", line 78, in exec_potodo
    issue_reservations = get_gh_issue_reservation()
  File "/Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages/potodo/potodo.py", line 21, in get_gh_issue_reservation
    issues = requests.get("https://api.github.com/repos/" + get_repo_name() + "/issues").json()
  File "/Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages/potodo/_github.py", line 14, in get_repo_name
    repo_url: str = get_repo_url()
  File "/Users/seluj78/.venvs/python-docs-i18n/lib/python3.7/site-packages/potodo/_github.py", line 9, in get_repo_url
    raise ValueError(f"Unknown error. `git get-url --all upstream|origin` returned {url}")
ValueError: Unknown error. `git get-url --all upstream|origin` returned fatal: not a git repository (or any of the parent directories): .git
(python-docs-i18n) ➜  ~
```

**Comment by Seluj78** [comment]
Needs more info
